export const GET_CONTENT_BY_ID = "HOME/GET_CONTENT_BY_ID";
export const GET_CONTENT_BY_ID_SUCCESS = "HOME/GET_CONTENT_BY_ID_SUCCESS";
export const GET_CONTENT_BY_ID_ERROR = "HOME/GET_CONTENT_BY_ID_ERROR";

export const CLEAR_CONTENT_ERROR = "HOME/CLEAR_CONTENT_ERROR";
